bk_ls = """BdbzzddChsWrRFbzBrszbhWMLNJHLLLLHZtSLglFNZHLJH
nnfMwqpQTMffHlNNLllHnZSS
cGpcMwfppfqcjcTCBBzWDsDbDrjzWz
LhfjhcdjcGdhFfdGfdjdvwCCZMvvLvWwMLCLSwZC
rDnsbmptPmlbQMCrQWQQBZQW
gltgVPngDPbptPsbPzVgmDldfTdfczThjJJjfMcJdFHjjH
dGlgDflTLLLrRLTLVdQLcQMnbvHbbFzNNvMbnHHn
sZjWJJCSjWqfCqSjSmJSbFvCzBMBBzHncHNvMBHN
twqqwpZwfrlwRwDGDR
zCGGFTQMQrsNRNGZdR
cLLQgPDpgcgmvPRHrwBdvrNZ
glWpmJWQDcJpQnpjSmbhFtMnqFfCVTCFCFFM
zNZWFNZBFrGTdBcZZBdJTrGrmgvppgDHwHmgVHCHCvCPDjzC
qtqqPnLSfLwvjvvgvvqH
MtbLLLQbRfPRfnbnnLMtnsbdBNsrGWNWcNcTBWZrrcrWcJ
sZwstbbDVlHtbhcrhhZLrRpNQN
jqGjjFjWnzWGgqWjJJNphnLMRhLhcrhcrSLN
qCJzFJdvmHvbtpbb
ZSRsvvQvZpsRQGJghClPCwGPChCP
FVdMLDdtDRdDcBtmcVFntwgJJTlnNPwJnlTlwlTPgN
VqttMWFmDbjbzrSWRQ
TsDSBcwshdwSCrgRWZBvgGRG
LPVJLqqJbbzpFqwpbvgGRmZPrmZgCvCCfr
tzJlJzQllFLqtwHhjNSdtthjDhTN
fsDLDDnwvnSdqLSsFSDfsLpbgVttPMpPNjMWVMNfpjgW
jhHmBmlrTBBHRPVtMZbppNPPZB
JmTTrTmjRTJqSQQSFqQw
HPzZFgPFMCHJCcZMcDQGwpLqPLqppwhGvv
BrWRqbqRsTSTqNddrVrthLQVwnpwphnvnDnGvGDn
tSbBfsRbTfqjJqjCqm
pCqrqzmqZzrmCCvCJwJPBRwJBWBmwWBJ
VqbqbjFLFfSHnfctBwDdDFTwtRRTDF
LVcnbjHLSqHnhbSGGppCMMZMphpNrQ
PhTcTPsSPCMvvhhMRPttbNWfNsWFNfWWtpNw
rdQrDbJBVVjrBVdLjHHHWNWwfHtzzNtFpZZptppg
JJVGGdddjDjDJmdjGqqRSbPMTvcRlqnnMlvT
SqGfTrBlSrrrfGGQvCnqZhZmPPhvJh
LdVNwgsjdjHmjWwDsDpwsHWtnCnQQQQNnvCnbJZQbNbtZZ
DjssDHLLVppDssdLspswFLVjzfFMTfSBcTRcrFSBzBTzmGzr
JSJJqlldpJlcdVWMlgMJrcCjrhzHCwTjHrQzwTzZ
bBvsGBGNFDNRFNFBRDPsDDHCChhhrZRQQzhjhCjTzWCr
FvbLFGDDtWDFBnPGFDWGqJMgJpSdVStllttlppVS
clpBdBQBsqGpQbVdqTTWRTSFgLLggffg
NzvwmHvZtZZgbDSCLDmfmm
jPJjthHzNwPvvjwjNzPzztZBlrccpbVGBQhlGBVlrpnpBs
NmFFGlGmzCrNWHvFmFWCFvQPTdDDlbbdgJPtgbbdPDcc
RwfBqLwZqffqnPbdDgVQDdtRbT
hnptqLMMLwqjMMjzSzHmhvNNrvvhhz
hqVrDdPdVDqjsDrjjqsfrrWlctvHJNLfvNcLHNNZRNZHvfZL
CSnWQSGBBSnmBnTmSbQbNZZMJNJMccGNHLZNNvNv
gFnmBmBnTCpwmBbgWVqjPsrsjplVrjlqPr
vgVgJJCphzFjzbwljwww
PWmfDgrPrPWlSWqSWlSZ
rrTHQTGTPHDDHgPrcrcPmDPhdtGvnvNnttJCdJhtGVnpdM
DDDhNgWNLWgDqDgtgtwSngjVSQdf
cvFrcGmBrrrCdSfSJQ
mBHzFFvFzmsBspsFsZqhqbWlWdPDlLHbqZ
TLNpGpRzwGQLLQRTwdvWdWbdbgdBlblb
FJDVzZzHfZHVzcHgnvHnvngvvc
MzDVSmZPPrqhGmCqQqLR
mqHWcBHVcgsbhhnTrrTg
fWftGtfJpwJMSdFDLFSGDGFnnNrbrhTNsZnrhTswZZnnsb
dSftppdSFStLDpQfLjWHQvWBmmqVjCqcVv
frfNzgvzzzJwJqpRcP
VdVSnGnHqhDDTdqhdLWmjMTmjMPjPmTsmsmjmR
BdGLSWtBSWDtVqdSDVGqtSSHFZFZtQbZlZfNgFffrgNrvgrl
jBVSjsJcLcqqjtgcmRFRNFFzFm
CnHnWQQGGWnnCnfvCTmZRZgNtfZtNDZPtNDtzl
mWWGGdmQQWwrHHMBBBhrBVqshBLBSL
cLtFcllvrslGLcLHVzDZQzzpznWzQtQZ
TmShfSSPJRRBBfSgmdfBJhDNVpGzVZpzQgZgbWzpnDGp
BhJPfSqdhqJRdBdPqTJBChvrFlHvvCGCccHsMscvrHvv
zfddZTpZLzLDfLtDCttdTfZPnlcPcnhjPDnlcjMchDPjnP
MQsFvFHJsQvmNvvswljgbPbwlwjnmcch
VFVqvqFQHqVJRVCBLpqTGMzCqtMZ
PZdVgNdQQcdcZQtGhnHtBlvlvWTnbBHWWH
CDJmzqFmMmLfqmzFwqfzfwMRvpRbTWBBWDnlnbnWnTNTnB
zFfffjCqwLJCfrCFjCLCzCMsjSZjQNPhQGVSQQZhsGjGgd
nbHntnqPQwTHwQVC
BzfSZSpcBZpzpPhSBjRTCBWTTRWTTTWR
pvZpzPzNfhddJGmmNnJb
GwTgWlvbgTwMrbwTrlWvwtHBNtNvBhBtdZcShHDtNS
PnndmnCmnJFnsmRdmFnnZDhRRScRQQHDtDNtcDQS
CLffLsmqqpJljVdlpMpWlr
dPCzBLTSLqmqdSCsmrTDVQjZfjfVVZnZhhhLGQ
wwFpgvPJNwgPPwvZGnQhbZQQFfQZbf
WvRwwJpHHgpNMNqdTdCdqrmHBPtm
DbWwjSGFSFfwGfCwDSSPPjLhgrrLWRJRgggJphLzpJLq
lQTnMHdcQBvlHMMZBcHHTrbzpdzgqrpLdqzzVRVRVV
vlvlNlBQvBZTQBnHnQTTBBPwPNCCsfSFmbSFfmGPwFmj
hGGQtbVjhRqlmqqrmDlpmw
gPMZsMgdssCPPsvrgZcTZTPSnnLLnBWDwLmwWwBnmWSnWNWB
TsvgMPdcgCfMdcsZJRQhVfVRVQFFQGtr
NfpFTTpFNbpZMRFrJMMMCv
dWJPngDWBtPVBdPVGHZzCGHZrrvZRSMSzv
WDDDVDPlWnLBVgnsgJmQJNqThNmbjlqbbh
vnznqvfrzzVzrvvnfVqztBtGbMCdGmCcdccJccCLCcpSSgcL
RQsDsljDlhssWshHhlhsHTlLbgJLpmgbbcMSpSSbcSJgjd
WswhhHWlRTsQDwWHTRhsvNVvwqzfVmNBtZNmnzzq
cjcPfLlQtPsZQlfHZJqVSFdVwmSRRqSSddwDvF
MgNbBgzgnwdPRFmSPn
CMGbNNMhCMzzPzBpTNPGBclLcLfsptHQfQlZssLcLf
slsdfpSlllpTVJJGgGDgHMdV
wrBQrbQrhQcpbQrhLwRBrjVVgGGPgZMtZMVhgMPMGHPg
QQwRnrwRbbRcmQmrjRnjpvNsNTNSlTmsTqCSvsNSWz
GWNwppdHdpmzgPFPCRmlCBPB
bSrJhJSsMhrJMDPRCPBlwVCtVSLV
QbsbwqQZvrJhhQrhZZrhchTfnTWGNvWpNnjHGvGjNdGT
NMZGmnMBWmwmNnGwHrHvHzfrvrVVVj
pSbDRLgbpJDPpRZRQjjFqVhhDFjDVqfrzv
sQQscLTZcsTpRsBnmlBcdCMBMtlc
hwWslbGWbRvLZvcscZ
gQnmmrNTmSnTfgwDwVwpJvJPJzLqLJTLLvRcZz
mrmnSrDNNQSmmwdggrrDbHMGhtdtGhGlhtClMGhM
qQdlGcvDQDQvDdmtPmmmlStbjSrm
CpNhzWTCTRznBMvwtTjMrHtSvj
nWzsfZCsBhNpZLgGdQDddvqd
ggjTjJWDVVVRTwQcZWvchshWhs
LmFfLfSmBtCttNLfCFBPFNBvvvhrcQdvsrsdSwdqcwrwSw
CHttltmlPLMHRTgJQDgRDTMb
RPJgCdhgPPSzvWDcCfGHDcvf
HbrrwBspTwWDDnqbZjjD
rQrFsrsstQMQHJdHQm
GVwQVGBZBNQwsjdNcMMlgJNPgj
SWFfSzTCSWFCSpgnJLSjpMdc
FhTbvrzrMrDCVHsVsHGBtHwv
FsqjjVzFVWFqRRWBssdpNSBHwJpHHJJdddSN
lQgmhvbTcgTgfhTQhSCFCGJHSlwNtJdGHG
vgZPbbfMhbTmchhjRFRnsDRPWVqzWz
cvwfjjcJjqhctvSpCgCFVhrFCrpC
mRsQmsMlNNzznWQlRnsMRQlSCpLNbpwSSSrwFLDFLLLgFp
zznlnGlmRmMlPZnGQzMszMRfccTjcBJjtJtJjqTZtfwBTt
PtCwCCVqbjNNqqvGssPmHGsHMfPH
dcddcWFDJJJcLczhWQdcDScZvHZgpGfsvMfSmsggSvvnvM
TTQmTDhdQQzdRwjBVrRwCwBbBr
BnBsFHCrcnBrMBPSmMSCmrcFqnZLddLhdhdGLvqLqgqnLJJp
WfjTlNVDTtjzNWTlVMWNlTwTJphdgpvJLGLdgghZvGLpwddq
zVjbVblVDlNTlbzTzDjllDTzHmHCsmcMHcSBrCBbrHBcBPSC
ddlcGQlCjQNGQmPLslZTlmTtfT
MDzMwSwqpzpDRpWRJwgZhttrZmTPfZmrmtrMZZ
JSqRBpJzwgDDpqDqvpBRdCjbCjQCFCbHvdGPjdHQ
bwzPwGLZMsbJMPPLGLMQzbhhQRvWWtVqVhgCVtWWQDqt
HddrHFnFNpVnVLhnvLRV
NLdrFjHTBrrdjFSpFmNBmSfZMwZMJJfSffbwzwPbczbJ
QTWSzTTLwTfwflSNJRdvGlRGcNgJBl
FnmmqrqbBBgRbHGc
MFZqrCVCqmZCprspFZmnnMsDfzWzDwSfjSwPQPTLhffwBLwj
npfgFRTZRRnDZLdgRfRrrjcWzGpWGGGQrjjWpP
vblVbvSShhVzHWjzzlrPWG
bVwqvCBtShqBhCCtqhNqCJRTTBDFJJLnJgDRWFBnWg
nHDNQvgvnNZHDnsGcjfNTrTfVrfL
SRWFSBRLtSFqjTrVVcsVjTSG
BdBbRttWBdbdWdbppmZlLmgwHvgQvgLZ
PQRZlpDDptQSclBMGVBdhVFGBMpf
nnrsTCWjLJsnsSMShhGJfwffwV
vjzqsjqgSHbbtvHZ
DgFmbdSDZbPgLbDDmFwZwgLSfccGcGvnvvngsGGnsGMNWsWs
HqztHHhHVhHjhRRhJtCVBCfNprMWpcMMJfsvvMsGscpG
tjVtBVTBtHHqCRqtzQwTPSNdSwPTTbPFDdml
sbmBmHZbRRRmwBmsSjHzRjmSCNFLNLLQNQhFgtQLzNztlrff
MpqPPDPVnGqrJpcqqJpMVlgtlLFLChCgChCCQgCtCD
VdcVVJvdrVWHbwHWBSSBRb
tPDVBzzNSNdDSQpMQMTQJMMQMN
LqSWSmbsmfQTTGZMWGCW
cLjLcbrjqmvfqLbfmqLwDBBzSHPzlwzcdBlnnP
SbnHrGHSrrhHJBrrScDfcPDMfpPGcGcpDL
QTpmpmmQWlZsTvVQDMgggFLgFcPf
zsCNlltCslzlTNsNlShwdJCpSqdHrBhpwr
JZmFrmLGjFZdDGrrVTvzmPVvRRVzwzzl
WBnfMDBqMsgDBqpBvzwVlCwRTRRPpvlw
WfghfttggfSnnqbDftfqSBBDQdHhZFFJrrHFjGJdGjFrjQLj
rNLRjrlVlrFRJzlsjrVlRFGCmnMtftgCNDDgDmCfqNgPNM
SpdBpdHbpHWhZqnCdtCGggqCPn
QHHvvWwWhwVVQRscVzGl
QffLtMQGMQfDMMwMTJwqWHvH
nSSFznjFcfjTgVJTJjvT
RrBpcfSNpRBcFshrCtQrDGLPQb
GctcMldStGwPPbcLsQTV
jhnzDgnHnnfPVwHQTTLTds
gBgzDDhzvqdGGvrtdvtm
PPwRWVTvRvPVLwRpMlzmbmsbHWjbbs
dFTFCNfdjzjFjsMF
SgdffSTrnnqCgdqgcNrfSZqVvVLRDPJZQwJBLPQPtLZwJJ
HSzDQftHphTBHFhr
WMmJsMJNLWNPmmsncjMJcjtvwggVvhFFFhjrVwrjrjppvT
WWPsJJCWCtZZZRGC
SfFZQDRLgpLlRgQRRRFWTsbhBhgTjbWBjhshgw
tHVNGjtzzHvMMJJhrWJNrTrPbP
jvVVvGCGtCmjHtdHzQQfDpSSlDRnFfQFmR
ZBBPfVVPPrVmrWZJzNdPznbnbSzznP
gvgpGqFFMgMcGgwLwGpcJNZSTZbdbdzNNSlqbTnn
ssZLgsMLQvcFpVrhCsmtWHjrrW
nFvhRnWWzBRPHQqcqqCqmFbd
SJDJgVprLfDfbJmHmWWHQtJW
wVsgWVSTgLjfSsVjVBRvRNwwGGRhNZhRMZ
wTRrRBCTPTBPlgMqgHCqggHLgg
dmDzpQpBdmWmWzzzDFzjGNMSWLSgLVGGLVNSLgSg
JbFdmQQJpjpptQbdJJmDmdtnZhZRflTlnTrTlrhBwPPc
jwSwssQbwbStlhRgtsVstn
zPzFdFFZccPDgntzVHHgghRz
vVVdfFmZPDMWZZBmGQbwJJGCLwwMwJCS
PLLffLFqqNLwSffbnVzzRf
lsmgTggChrgDtZsZVblMVJMznVnwMBnb
hDZZTmZvhTgstvwNFdqpWQcqvP
mmWwpwqtmmHTqHpprRZQPPZLZWSFRFRB
gzcgscgbfvhRRNZQRRQPvr
JsjhcshCfJgrrpttTCTplH
TvNrvNrJfWWvtJLTHhvZZhQQwVGZZhbV
mFCPmBMPlPsPPBsMFPszbHQJwwHHhbZVQVzjhGHZ
qmlBsdCSmJBmsBBMnMMTDWDNcLrDprSNcWDNrW
HSnHCVqTddFHSVqFqdStSQGQwRzQCzCRzGRRGNPQwz
jhlBpgNvlfZjlfvmpgfgfBrMRRwMMPPLQMZRPMWMMZPQ
hflfpgjfBfDcpchlpvndbHFDdHqSqNVqNVdn
QBfhlVNfHSZHfVCVHSQfZfTCctdvdDTRtjDCtTRsjsvj
brrWWqzFWzwWbswDchhTRtDhjT
gbrFLnpzqrWPgqpLWrhnHGZlSfLfHfQBGVfHHNVG
hcFmVScmQBVhtcvfHLfvHSnbHRLn
lzQqlDqgpWPvJfRnlNJvww
PjCCCPgDgqGzmMtCQstZmBFs
GrnrHrmVVFMFhSSbSfhR
zjTqLtBjjdWdWTLshMZMDbPNRMSSqSPNfD
dTWjdtwWhjWTBzcnrpcwmQpCwcpw
BgtVBsgVVJhgGsSGJbghJqbsjLfZmLjmmtfZndNNZFFZNLdm
MHTlzlwHSvPvzMSPCTMQCNZdjjmnfQjdZfNLjF
HMDTwPDpzrTzpScBghDbVqRBgRBJsR
qjCsTmrrnnCmhcFrCjqmThRlbHGvJGvvvbRbbJRcQJRG
fVBBTfMdSZLNZgPdgglGRdbtbtJRllJWJtWb
TSZZSpNMPBLgpZLVgppBDFhzDmjrnzhjssFqDhzFnn
MDtDMWmMQmdzmMMqvlGfRcjzgpcPPjczPl
sZsHJWNJFJNbWFBhFBnnbVclbVVPglfcRggffGGpjl
srHWLNZZJdSLSdvDMw
BFqsPnsZcgnncggccqsqqpDPtDWPpPNTNSNThrWtSj
dQbfQQJJdwdmFRbJLRJdMrfDWrjpDrrprhDDDDNWWD
QGwdJmCFJZvGsvvncB
GRRNSjrffGTSPrNTffSgcJTwWJZbbZvwvwtVwWVJZv
CMcFsqmBQzMzshsBQBQvLWmJVwZtpJLJwJLvwt
qBzChnQlzMcRSnnRRjHGGg
dPPbPWNdTBbDpHPHpNsgzvFlglvHzvSFzCFF
fntqhGhRMhnnnGGCVMRhCVlSjswFvvjzjSzvQVSgsl
MMqqJJRCnMhZLCRhtPNrpZPDDWTDTrNBmD
VjVGNTNlNchVjNGRWrSWWtZtRrzncR
BTbbbwDmCDLTbDwfHmzZMmRrWtzPrZSZtrrz
qDLLqvwLBsfBbBdQFQTJhqThVTQJ
qBqPBGZflhrWznzZZdsnzv
FmHRcCCsCDwDbjtzdjWbdz
cTRwCCNHFNmwRgmFTNCFTJqqfqPJsPhPBlsrsfGf
JTNhhNrCTcWpJJcpWw
LLdLsfMsdStbtggLbnTpwfWDzpjvnnjzcz
MqSZsgbMbGFbZtgTSZSFSLhhmHlBQlmrmrPHHCPPZPBr
GgjjgpGvpJJtjgvPrJttsLjVwCsQsQNLsfLfMVCl
RddqZqzcZdSWcHdcqQfQLMwVflfNQNMQ
FncWTRcFlHWFmcFTgPJhGvDgpnnhhGtG
ZGPFJsPQCbZCCbgz
nrvrnGWTwwqTBRcpCRRg
DnGWDldNmSLSMdMQ
ScDmPPPmjmjjWgtdSmdmCnNqVQVVrNRTZTQTQDHHZGNH
wbbMhLvMJpRwJQrJGHqQGrQHqr
wzhspwpppswsMFLmtnzjdcmdPRWPtS
fPlLTtBlTjDbWcTMJcncWqss
LdvLrLpCRRQQmvhhVNpwRMWJZcFMZWJwJFFFwZsGcs
prrRVpvvRVNmRvvzHjHPlzPLSffbbPHS
bbCbzsQbBzbBFbFzFfJHfVJPfVPtzZttpm
hwvrjDDwjcDcvdnNvwdnwwDPpNtNMVtPpJpRmVMPfmtVZR
mmqDWjhcqhwvDDdTsSGGCbQGSBBLTGGl
wthtwrBQhhSrqJJVLMRPPtJLPF
vbmbZqfqgsfHmcllmLLJNLJMNFJNNvPGJn
jHlDscllClCCgbZzhWqBzBQzprWCqS
DwpDlwDwllhJwbDFNDwFPhDnQnZZzVVnnBrtNznzSSzZrr
MHPfWRTgWzTQmSTTZt
GdPjHLRMCfcGvwqDGbFq
NGdNpDPdNGLppLpwSNFFFDLwnnZbMnrHlHZQcHbcnHQcPcQM
jBgBsjssgjWJVGhBfhvJVnMlbnZQVrrrlHCcCZrl
sRBgvRffhhtvtBgvjgttWBJTLmFLLwdwzFdqLDDDqFGdLFTd
RBzRGRGBgnrPJrRGGWWbDggZTSTVZVFFSVZZdw
tfmLhjfshNNsqpppfjHdwVdQZbVbQFVVTmSVDV
jvqtwHqCNLNsNhNfjssLCzGJWcBRJRBCBBBrrWnGrG
cGDBdNFdNdDStNtGdGQGscDMvZjjZWMvMLjsjjLZjLsJLv
fbRnRzHVPClfRlbbmfHRlPvZvMLpqjvZJqZMpzMpZjBZ
gfbfBgCHCPVNhNGgTtFDcF
ljjvLZvvllFnlLJLJjLWFQrVssFpsGMFpNMGsr
qbHSqHTcHChqCmTSRqqBVpVdBQsVQQGHdMprWV
DbtcCqRhhTRmDnPMlLgfgztlZZ
QtMQzPZcbtGgTtLvtf
HwcDsdVVDnNSGLhwvffJvfTT
CSsdSHNmSDHcCqqcrrzQcC
nDNDfmMnmDJRNfJJdMDRBdwjcTtsSHvBTswTjwLtsCts
QcbQrZZggGWVVWbZZjStswCSCCttGCwLvC
ZgZgbzVglVbchVVrVhFWWpnnpNJmJMqDfMJnMRqNDDMD
WMfNvsjWGjsqFjqTRRQVJztDzVmJHbft
ZPhplcrLrmzQGzmz
ZPddLPlcSclhZChndMvgTjjWNGWMGWBj
nDLjMchghDcljfjffpfsqTmGCTGszGZVVzHV
wdFJPFrQRwSNbjVQCTGsHZHmHCHs
BRJJSddvdBrJwrBRNRFRSPRjvclLpWhpglgWpLplltnMgh
BbVRzMcpbMNMHMTJmWdljdlJjT
GtsqFnfvGSFqGfQvgnWWZlLlLjZWtWldPmlT
sSsFqsqsGghwQQmfGRHbbVczbwwBpBpHcw
BBFCBJCsGJBBgvgsvTlVhgNg
ZnLdjRQddLRnZrlScHRVTTSHhRvg
fnnjZLWdrnqdWrrPLddqVqBzGDJJFGCBDfJmbDzFMbmB"""
bk_con = bk_ls.splitlines()

# create alphabet list
alphabet = {}
start = ord('a')
# input lowercase letters
for i in range(26):
    alphabet[chr(start + i)] = i + 1

# input uppercase letters
start = ord('A')
for j in range(26):
    alphabet[chr(start + j)] = 27 + j

# find intersection of two list
def intersect(list_a, list_b):
    return list(set(list_a) & set(list_b))

score = 0
for ls in bk_con:
    ls = list(ls)
    mid_index = len(ls)//2
    ls_a, ls_b = ls[mid_index:], ls[:mid_index]
    score += alphabet[intersect(ls_a, ls_b)[0]]
    print(ls_a)
    print(ls_b)
    print(intersect(ls_a, ls_b))

print(score)

# get common of three
score = 0
for i in range(0, len(bk_con), 3):
    ls_a, ls_b, ls_c = set(bk_con[i]), set(bk_con[i + 1]), set(bk_con[i + 2])
    score += alphabet[list(ls_a.intersection(ls_b, ls_c))[0]]
print(score)

